services:
  hitzak:
    build:
      context: . # https://github.com/draumaz/hitzak.git
      dockerfile: Dockerfile
    container_name: hitzak_app
    ports:
      - "8039:8039"
    environment:
      - PORT=8039
      - NODE_ENV=production
    volumes:
      - hitzak_data:/app/db
    restart: unless-stopped

volumes:
  hitzak_data:
