"use client";

import { useState, useEffect, useRef } from "react";
import { Volume2, Keyboard, Sparkles } from "lucide-react";
import { sound } from "@/lib/sound";
import { cn } from "@/lib/utils";

interface OptionItem {
  id: number;
  text: string;
  correct: boolean;
  order?: number;
}

interface TranslateChallengeProps {
  question: string;
  prompt?: string;
  audioText?: string;
  grammarTip?: string;
  options: OptionItem[];
  selectedTokens: OptionItem[];
  onSelectToken: (token: OptionItem) => void;
  onRemoveToken: (token: OptionItem) => void;
  setSelectedTokens: (tokens: OptionItem[]) => void;
  isKeyboardMode: boolean;
  status: "idle" | "correct" | "wrong";
}

function normalizeWord(word: string): string {
  return word
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, "")
    .trim();
}

function renderOptionText(text: string, buffer: string) {
  if (!buffer) return text;
  const cleanBuf = buffer.toLowerCase();
  const lowerText = text.toLowerCase();
  const idx = lowerText.indexOf(cleanBuf);
  if (idx === -1) return text;
  return (
    <span>
      {text.slice(0, idx)}
      <span className="text-[#1899d6] underline font-black">
        {text.slice(idx, idx + cleanBuf.length)}
      </span>
      {text.slice(idx + cleanBuf.length)}
    </span>
  );
}

export const BASQUE_TO_ENGLISH: Record<string, string> = {
  "gizon": "man",
  "emakume": "woman",
  "mutil": "boy",
  "neska": "girl",
  "ni naiz": "I am",
  "zu zara": "you are",
  "hura da": "he is",
  "bat": "one",
  "kaixo": "hello",
  "aitor": "Aitor (male name)",
  "mikel": "Mikel (male name)",
  "terese": "Terese (female name)",
  "miren": "Miren's (female name)",
  "ni": "I",
  "naiz": "am (izan)",
  "zu": "you",
  "zara": "are",
  "hura": "that over there / he / she / it",
  "da": "is",
  "emakaume": "woman",
  "gizona": "man",
  "emakumea": "woman",
  "mutila": "boy",
  "ere": "also",
  "irakasle": "teacher",
  "irakaslea": "teacher",
  "ikasle": "student",
  "ikaslea": "student",
  "epa": "hi",
  "gu gara": "we are",
  "zuek zarete": "you all are",
  "haiek dira": "they are",
  "eta": "and",
  "gizonak": "men",
  "emakumeak": "women",
  "mutilak": "boys",
  "neskak": "girls",
  "irakasleak": "teachers",
  "ikasleak": "students",
  "aintza": "Aintza (female name)",
  "jon": "Jon (male name)",
  "joseba": "Joseba",
  "karmele": "Karmele (female name)",
  "dira": "are",
  "emakaumeak": "women",
  "gara": "are",
  "gu": "we",
  "haiek": "those over there, plural of hura / they",
  "zarete": "are",
  "zuek": "your (plural)",
  "arratsalde on": "Good afternoon",
  "barkatu": "sorry",
  "egun on": "Good morning",
  "eskerrik asko": "Thank you",
  "ondo": "well / fine",
  "ni nago": "I am",
  "bai": "yes",
  "zer moduz": "How are you?",
  "al": "question word",
  "arratsalde": "afternoon",
  "asko": "a lot / lots / very much",
  "berdin": "same",
  "egun": "day",
  "eskerrik": "thanks",
  "on": "good",
  "moduz": "are you",
  "nago": "am (egon)",
  "nor": "who",
  "zer": "what",
  "agur": "goodbye",
  "bihar": "tomorrow",
  "arte": "until",
  "ez da ezer": "It is nothing.",
  "gabon": "good night",
  "gero": "then / after / later",
  "berandu": "late",
  "ongi etorri": "welcome",
  "autobusa": "bus",
  "ez": "not, no",
  "ezer": "anything",
  "ongi": "well",
  "etorri": "come",
  "mesedez": "please",
  "nortzuk": "who (plural)",
  "autobus": "bus",
  "kotxe": "car",
  "autobusak": "buses",
  "kotxeak": "cars",
  "edo": "or",
  "kotxea": "car",
  "erizain": "nurse",
  "gidari": "driver",
  "mediku": "doctor",
  "polizia": "police officer",
  "tour gida": "tour guide",
  "turist": "tourist",
  "erizaina": "nurse",
  "erizainak": "nurses",
  "gidaria": "driver",
  "gidariak": "drivers",
  "ingeniari": "engineer",
  "medikua": "doctor",
  "medikuak": "doctors",
  "poliziak": "police officers",
  "tour": "tour",
  "gida": "guide",
  "gidak": "guides",
  "turista": "tourist",
  "turistak": "tourists",
  "ni nintzen": "I was",
  "zu zinen": "you were",
  "hura zen": "he was",
  "gu ginen": "we were",
  "zuek zineten": "you(plural) were",
  "haiek ziren": "they were",
  "orain": "now",
  "baina": "but",
  "gaur": "today",
  "ginen": "we were",
  "nintzen": "I was",
  "zen": "was",
  "zinen": "you were",
  "zineten": "you (plural) were",
  "ziren": "they were",
  "etxekoandre": "housewife",
  "lagun": "friend",
  "camarero": "waiter",
  "sukaldaria": "cook",
  "apaiz": "priest",
  "arrotz": "stranger",
  "apaiza": "priest",
  "apaizak": "priests",
  "arrotza": "stranger",
  "arrotzak": "strangers",
  "camareroa": "the waiter",
  "camareroak": "waiters",
  "etxekoandrea": "housewife",
  "etxekoandreak": "housewives",
  "laguna": "friend",
  "lagunak": "friends",
  "langile": "worker",
  "langilea": "worker",
  "langileak": "workers",
  "sukaldariak": "cooks",
  "beltz": "black",
  "zuri": "to you / white",
  "gorri": "red",
  "laranja": "orange",
  "hori": "that / yellow",
  "berde": "green",
  "urdin": "blue",
  "gris": "gray",
  "poltsa": "purse",
  "zein": "which",
  "koloretakoa": "color",
  "beltza": "black",
  "berdea": "green",
  "berdeak": "green",
  "gorria": "red",
  "grisa": "gray",
  "grisak": "gray",
  "horia": "yellow",
  "horiak": "yellow",
  "laranjak": "orange",
  "poltsak": "purses",
  "urdina": "blue",
  "urdinak": "blue",
  "zuria": "white",
  "zuriak": "white",
  "baizik": "but rather",
  "hotel": "hotel",
  "eliza": "church",
  "ostatu": "mini-hotel",
  "denda": "store",
  "etxe": "house",
  "dendak": "stores",
  "hotela": "hotel",
  "hotelak": "hotels",
  "kolore": "color",
  "kolorea": "color",
  "koloreak": "colors",
  "ostatua": "mini-hotel",
  "handi": "big",
  "txiki": "small",
  "altu": "tall",
  "motz": "short",
  "labur": "short",
  "gizen": "fat",
  "argal": "thin",
  "gazte": "young",
  "zahar": "old",
  "more": "purple",
  "altua": "tall / high",
  "altuak": "tall / high",
  "apiza": "priest",
  "argala": "thin",
  "gaztea": "young",
  "gizena": "fat",
  "handia": "big",
  "laburra": "short",
  "morea": "purple",
  "motza": "short",
  "zaharra": "old",
  "eder": "handsome / beautiful",
  "itsusi": "ugly",
  "polit": "pretty",
  "berri": "new",
  "azkar": "fast",
  "motel": "slow",
  "itziar": "Itziar (female name)",
  "azkarrak": "fast",
  "azkarra": "fast",
  "berria": "new",
  "berriak": "new",
  "ederra": "beautiful",
  "ederrak": "handsome / beautiful",
  "euskaldun": "Basque",
  "euskalduna": "Basque person",
  "euskaldunak": "Basque people",
  "gazteak": "young",
  "idazkaria": "secretary / clerk",
  "itsusia": "ugly",
  "itsusiak": "ugly",
  "motela": "slow",
  "motelak": "slow",
  "polita": "pretty",
  "politak": "pretty",
  "animalia": "animal",
  "dortoka": "a turtle",
  "hontz": "owl",
  "katu": "cat",
  "oilasko": "chicken",
  "txakur": "dog",
  "txori": "bird",
  "lili": "Lili (LibreLingo Turtle)",
  "animaliak": "animals",
  "austobusa": "bus",
  "begira": "look",
  "dortokak": "turtles",
  "hontza": "owl",
  "hontzak": "owls",
  "katua": "a cat",
  "katuak": "cats",
  "oilaskoa": "a chicken",
  "oilaskoak": "chickens",
  "txakura": "a dog",
  "txakurrak": "pigs",
  "txikia": "small",
  "txoria": "bird",
  "txoriak": "birds",
  "zahara": "old",
  "ahuntz": "goat",
  "ardi": "sheep",
  "arrain": "fish",
  "behi": "cow",
  "sagu": "mouse",
  "suge": "snake",
  "txerri": "pig",
  "zaldi": "horse",
  "marroi": "brown",
  "ahuntza": "goat",
  "ahuntzak": "goats",
  "ardia": "sheep",
  "ardiak": "sheep (plural)",
  "arraina": "fish",
  "arrainak": "fish (plural)",
  "behia": "cow",
  "behiak": "cows",
  "beltzak": "black",
  "handiak": "big",
  "laburrak": "short",
  "marroia": "brown",
  "motzak": "short",
  "sagua": "mouse",
  "saguak": "mice",
  "sugea": "snake",
  "sugeak": "snakes",
  "txerria": "pig",
  "txerriak": "pigs",
  "uso": "pigeon",
  "usoa": "a pigeon",
  "usoak": "pigeons",
  "zaldia": "horse",
  "zaldiak": "horses",
  "ahul": "weak",
  "indartsu": "strong",
  "jator": "nice",
  "luze": "long",
  "txar": "bad",
  "euskal": "basque",
  "ahula": "weak",
  "ahulak": "weak",
  "euskala": "basque (ad)",
  "euskalak": "basque (ad)",
  "indartsua": "strong",
  "indartsuak": "strong",
  "jatora": "nice",
  "jatorak": "nice",
  "laburak": "short",
  "luzea": "long",
  "luzeak": "long",
  "ona": "good",
  "onak": "good",
  "txarra": "bad",
  "txarrak": "bad",
  "hau": "this",
  "hauek": "These, plural of hau",
  "eskola": "school",
  "liburu": "book",
  "iziar": "Iziar (name)",
  "horiek": "Those, plural of hori",
  "liburua": "books",
  "liburuak": "books",
  "nire": "my",
  "zure": "your",
  "bere": "his / hers / its",
  "gure": "our",
  "zuen": "yours",
  "haien": "their",
  "apaizaren": "priest's",
  "etxekoandrearen": "the housewife’s",
  "emakumearen": "the woman’s",
  "gidariaren": "driver's",
  "gizonaren": "man's",
  "irakaslearen": "the teacher’s",
  "ikaslearen": "the student’s",
  "erizainaren": "the nurse’s",
  "poliziaren": "the police officer’s",
  "anitzarenak": "Anitza's (female name, plural object)",
  "mirenen": "Miren's (female name)",
  "xabieren": "Xabier's (male name)",
  "mikelenak": "Mikel's (male name)",
  "aterki": "umbrella",
  "arkatz": "pencil",
  "arkatza": "pencil",
  "arkatzak": "pencils",
  "aterkia": "umbrella",
  "aterkiak": "umbrellas",
  "baloi": "ball",
  "baloia": "ball",
  "baloiak": "balls",
  "bizikleta": "bicycle(Noran case)",
  "bizikletak": "bicycles",
  "boligrafo": "pen",
  "boligrafoa": "pen",
  "boligrafoak": "pens",
  "erloju": "watch / clock",
  "erlojua": "watch / clock",
  "erlojuak": "watches / clocks",
  "etxea": "house",
  "gorriak": "red",
  "ikasleenak": "students'",
  "lagunen": "friend's",
  "lagunaren": "friend's",
  "noren": "whose",
  "norena": "whose",
  "norenak": "whose (plural)",
  "txikiak": "small",
  "medikuen": "doctors’",
  "erizainen": "of the nurses",
  "arrotzen": "strangers’",
  "camareroen": "waiters’",
  "mutilen": "boys’",
  "nesken": "girls’",
  "sukaldarien": "cooks’ / chef’s",
  "turistaren": "tourist’s",
  "turisten": "tourists'",
  "aitorren": "Aitor's (male name)",
  "arantxaren": "Arantxa’s",
  "josabaren": "Josaba’s",
  "jonen": "Jon’s",
  "alkondara": "shirt",
  "arropak": "clothes",
  "berokia": "coat",
  "betaurrekoak": "glasses",
  "eraztuna": "ring",
  "eskularruak": "gloves",
  "galtzerdiak": "socks",
  "gerrikoa": "belt",
  "alkandora": "shirt",
  "alkandorak": "shirts",
  "armarria": "coat",
  "arropa": "clothing",
  "behiaren": "cow (Noren)",
  "dortokaren": "turtle's",
  "eraztun": "ring",
  "gerriko": "belt",
  "ingeniariak": "engineers",
  "neskaren": "girl's",
  "nirea": "mine",
  "zurea": "yours",
  "berea": "his / hers / its",
  "gurea": "ours",
  "zuena": "yours (plural)",
  "haiena": "theirs",
  "motxila": "backpack",
  "berokiak": "coats",
  "eraztunak": "rings",
  "gerrikoak": "belts",
  "gureak": "ours",
  "motxilak": "backpacks",
  "nireak": "mine",
  "zaharrak": "old",
  "zuenak": "yours (plural)",
  "zureak": "yours",
  "bereak": "his/hers/its (plural object)",
  "haienak": "theirs (plural object)",
  "mikelen": "Mikel's (male name)",
  "anitzaren": "Anitza's (female name)",
  "beroki": "coat",
  "betaurreko": "glasses (single)",
  "eskularru": "glove",
  "eskularrua": "glove",
  "galtzerdi": "socks(noren case)",
  "gona": "skirt",
  "gonak": "skirts",
  "hontzaren": "owl's",
  "jaka": "jacket",
  "jakak": "jackets",
  "jertse": "sweater",
  "jertsea": "sweater",
  "marroiak": "brown",
  "oilaskoaren": "chicken's",
  "prakak": "trousers",
  "soinekoa": "dress",
  "txanoa": "hat",
  "txanoak": "hats",
  "txerriaren": "pig (Noren)",
  "txoriaren": "bird's",
  "zaldiaren": "horse's",
  "zapatak": "shoe",
  "zorro": "wallet",
  "zorroa": "wallet",
  "zorroak": "wallets",
  "moreak": "purple",
  "soineko": "dress",
  "soinekoak": "dresses",
  "txano": "hat",
  "zu zaude": "you are",
  "hura dago": "he is",
  "gu gaude": "We are",
  "zuek zaudete": "you (plural) are",
  "haiek daude": "they are",
  "zuhaitz": "tree",
  "non": "where",
  "kanpo": "outside",
  "barruan": "inside",
  "ahizpa": "sister of a sister",
  "ahizpan": "sister's",
  "aiton-amonak": "grandparents",
  "aiton": "grandfather",
  "aitona": "grandfather",
  "aitonaren": "grandfather's",
  "aita": "father",
  "aitaren": "father's",
  "alaba": "daughter",
  "alabak": "daughters",
  "alabaren": "daughter's",
  "ama": "mother",
  "amaren": "mother's",
  "amon": "grandmother",
  "amona": "grandmother",
  "amonaren": "grandmother's",
  "anaia": "brother of a brother",
  "anaian": "brother of a brother's",
  "arreba": "sister of a brother",
  "badaude": "there are",
  "biloba": "grandson / granddaughter",
  "bilobak": "grandchildren",
  "dago": "is",
  "daude": "are (egon)",
  "elizan": "in a church",
  "elizetan": "at churches",
  "emaztea": "wife",
  "etxean": "in a house",
  "gaude": "are (egon)",
  "gurasoak": "parents",
  "hotelan": "in the hotel",
  "iloba": "niece / nephew",
  "ilobak": "nieces / nephews",
  "ingeniaria": "engineer",
  "izeba": "aunt",
  "izebare": "aunt's",
  "kanpoan": "outside",
  "lehengusu": "cousin (male)",
  "lehengusua": "cousin (male)",
  "lehengusina": "cousin (female)",
  "mutillaguna": "boyfriend",
  "neba": "brother of a sister",
  "neskalaguna": "girlfriend",
  "osaba": "uncle",
  "osabaren": "uncle's",
  "ostatuan": "in a mini-hotel",
  "poltsan": "in the purse",
  "seme": "son",
  "semea": "son",
  "semeak": "sons",
  "semearen": "son's",
  "seme-alba": "children",
  "seme-albak": "children / sons and daughters",
  "senarra": "husband",
  "txakurra": "pig",
  "ume": "child",
  "umea": "child",
  "umeak": "children",
  "zaude": "are (egon)",
  "zaudete": "are (egon)",
  "zuhaitzean": "in the tree",
  "madril": "Madrid (city)",
  "espainia": "Spain",
  "europa": "Europe",
  "hemen": "here",
  "hor": "there",
  "han": "there",
  "euskal herrian": "in Basque Country",
  "baso": "glass",
  "laku": "lake",
  "espainian": "in Spain",
  "europan": "in Europe",
  "herrian": "country",
  "madrilen": "in madrid",
  "badago": "there is",
  "basoan": "in the forest",
  "lakuan": "in the lake",
  "mendi": "mountain",
  "irun": "Irun (city)",
  "donostia": "San Sebastian",
  "gasteiz": "Vitoria",
  "bilbo": "Bilbao",
  "kale": "street",
  "frantzia": "in France",
  "ibai": "river",
  "bilbon": "in Bilbao",
  "francia": "France",
  "gasteizen": "in Vitoria (city in Basque Country)",
  "irunen": "in Irun",
  "basoa": "glass",
  "basoetan": "in the forests",
  "ibaia": "river",
  "ibaiaren": "river (Noren)",
  "ibaietan": "of the rivers",
  "kalea": "street",
  "kalean": "in/on a street",
  "kaletan": "in the streets",
  "lakuetan": "in the lakes",
  "mendian": "in, on the mountain",
  "mendietan": "on the mountains",
  "mendiaetan": "upon the mountains",
  "zuhaitza": "tree",
  "zuhaitzetan": "in trees",
  "bi": "two",
  "hiru": "three",
  "lau": "four",
  "bost": "five",
  "euro": "euro",
  "zenbat": "how many",
  "how much": "zenbat",
  "how many": "zenbat",
  "zero": "zero",
  "sei": "six",
  "zazpi": "seven",
  "zortzi": "eight",
  "bederatzi": "nine",
  "hamar": "ten",
  "gehi": "plus",
  "ken": "minus",
  "minus": "ken",
  "plus": "gehi",
  "sukaldari": "cook",
  "two": "bi",
  "hamaika": "eleven",
  "hamabi": "twelve",
  "hamahiru": "thirteen",
  "hamalau": "fourteen",
  "hamabost": "fifteen",
  "hamasei": "sixteen",
  "hamazazpi": "seventeen",
  "hemazortzi": "eighteen",
  "hemeretzi": "nineteen",
  "aitona-amonak": "grandparents",
  "anearenak": "Anea's (female name, plural object)",
  "gurasoen": "parents'",
  "izebaren": "aunt's",
  "ahizparen": "sister's",
  "anaiaren": "brother's",
  "arrebaren": "sister's",
  "jatorra": "nice",
  "ni bizi naiz": "I live",
  "zu bizi zara": "You live",
  "hura bizi da": "He lives",
  "gu bizi gara": "We live",
  "zuek bizi zarete": "You (plural) live",
  "haiek bizi dira": "They live",
  "baserri": "farm / farmhouse",
  "batean": "in a",
  "baserria": "farm / farmhouse",
  "baserrian": "on a farm",
  "bizi": "live",
  "donostian": "in San Sebastian",
  "francian": "in France",
  "ibaian": "in a river",
  "seme-alabak": "children / sons and daughters",
  "ni biziko naiz": "I will live",
  "zu biziko zara": "You will live",
  "hura biziko da": "she will live",
  "gu biziko gara": "We will live",
  "zuek biziko zarete": "You (plural) will live",
  "haiek biziko dira": "They will live",
  "arrano": "Arrano (name of a street)",
  "frantzian": "in France",
  "ahizpak": "sisters of a sister",
  "anaiak": "brothers of a brother",
  "arrebak": "sister of a brother",
  "biziko": "will live",
  "lehengusuak": "cousins (male)",
  "nebak": "brothers of a sister",
  "ni bizi  nintzen": "I lived",
  "zu bizi  zinen": "You lived.",
  "hura bizi zen": "She lived.",
  "gu bizi ginen": "We lived",
  "zuek bizi  zineten": "You (plural) lived",
  "haiek bizi ziren": "They lived",
  "italian": "in Italy",
  "duela": "ago",
  "urtebete": "one year",
  "eskolan": "in a school",
  "urte": "year",
  "egon": "stayed / stay (command) / do",
  "erori": "fell",
  "eseri": "sat",
  "esnatu": "woke",
  "ibili": "walked",
  "iritsi": "arrived",
  "atzo": "yesterday",
  "donostiara": "To San Sebastian",
  "dendan": "in a store",
  "hotelean": "in a hotel",
  "gaur goizean": "this morning",
  "goiz": "early",
  "garaiz": "on time",
  "autobusean": "on the bus",
  "goizean": "morning",
  "liburuen": "on books",
  "egunero": "every day",
  "gauero": "every night",
  "hilero": "every month",
  "urtero": "every year",
  "egoten": "stay/being at a location",
  "erortzen": "fall",
  "eserten": "sit",
  "esnatzen": "wake up",
  "ibiltzen": "walk",
  "iristen": "arrive",
  "bostetan": "at five",
  "hamarretan": "at ten",
  "seietan": "at six",
  "egongo": "will stay/be at a location",
  "eroriko": "will fall",
  "eseriko": "will sit",
  "esnatuko": "will wake up",
  "ibiliko": "will walk",
  "iritsiko": "will arrive",
  "noiz": "when",
  "izebak": "aunts",
  "osabak": "uncles",
  "atera": "left",
  "joan": "went (+izan) / go (command)",
  "etzan": "lay down",
  "poztu": "were glad, rejoiced",
  "geratu": "stay",
  "den astean": "last week",
  "astean": "in a week / week",
  "ateratzen": "leave",
  "bederatzietan": "at nine",
  "beti": "always",
  "den": "last",
  "dendetatik": "from stores",
  "elizatik": "from church",
  "elizaetatik": "from churches",
  "eskolatik": "from school",
  "eskolaetatik": "from schools",
  "eskolak": "schools",
  "etortzen": "come",
  "etxetik": "from home, from a house",
  "etzaten": "lie down",
  "hamaiketan": "at eleven",
  "hoteletatik": "from hotels",
  "joaten": "go (+izan) / going",
  "lehengusinak": "cousins (female)",
  "maiz": "often",
  "ohi": "usually",
  "ostatutik": "from a mini-hotel",
  "ostatuetatik": "from mini-hotels",
  "pozten": "am glad / rejoice",
  "zortzietan": "at eight",
  "aterako": "will leave",
  "etorriko": "will come",
  "joango": "will go (+izan)",
  "etzango": "will lie down",
  "poztuko": "will be glad / will rejoice",
  "geratuko": "will stay",
  "gutxitan": "seldom",
  "inoiz ez": "never",
  "donostiatik": "from San Sebastian",
  "europatik": "from Europe",
  "espainiatik": "from Spain",
  "frantziatik": "from France",
  "gasteiztik": "from Vitoria",
  "inoiz": "ever",
  "ni nator": "I am coming",
  "zu zatoz": "You are coming",
  "hura dator": "He is coming",
  "gu gatoz": "We are coming",
  "zuek zatozte": "You all are coming",
  "haiek  datoz": "They are coming.",
  "nondik": "from where",
  "gasteizetik": "from Vitoria",
  "parisetik": "from Paris",
  "dator": "He is coming / She is coming / It is coming",
  "datoz": "They are coming.",
  "gatoz": "We are coming",
  "hoteletik": "from a hotel",
  "mendietatik": "from the mountains",
  "nator": "I am coming",
  "zatozte": "You (plural) are coming",
  "zatoz": "You are coming",
  "banku": "bank",
  "aireportua": "airport",
  "tren": "train",
  "geltoki": "station",
  "zinema": "cinema / movie theater",
  "aireportutik": "from the airport",
  "bankutik": "from the bank",
  "geltokitik": "from the station",
  "zinematik": "from the cinema / from the movie theater",
  "nentorren": "I was coming",
  "zentozen": "You were coming",
  "zetorren": "he was coming / she was coming / it was coming",
  "gentozen": "We were coming",
  "zentozten": "You (plural) were coming",
  "zetozen": "They were coming",
  "nora": "where (to)",
  "noa": "I am going",
  "zoaz": "you are going",
  "doa": "he is going / she is going / it is going",
  "goaz": "we are going",
  "zoazte": "you (plural) are going",
  "doaz": "they are going",
  "lakura": "to the lake",
  "elizara": "to a church",
  "hotelera": "to the hotel",
  "ostatura": "to the mini-hotel",
  "bankura": "to the bank",
  "basora": "to the forest",
  "basotik": "from the forest",
  "dendara": "to the store",
  "geltokira": "to the station",
  "ibaira": "to the river",
  "kotxera": "to the car",
  "mendira": "to the mountain",
  "nindoan": "I was going",
  "zindoazen": "you were going",
  "zihoan": "she was going / he was going",
  "gindoazen": "we were going",
  "zindoazten": "you (plural) were going",
  "zihoazen": "they were going",
  "autobusetara": "to the buses",
  "etxeetara": "to the houses",
  "zuhaitzetara": "to the trees",
  "bizikletaetara": "to the bicycles",
  "aitak": "fathers",
  "amak": "mothers",
  "amonak": "grandmothers",
  "basserietara": "to the farm/farm houses",
  "dendaetara": "to the stores",
  "elizaetara": "to the churches",
  "eskolaetara": "to schools",
  "mendietara": "to the mountains",
  "zuhaitzak": "trees",
  "italia": "Italy",
  "italiara": "To Italy",
  "alemania": "Germany",
  "alemaniara": "To Germany",
  "irunera": "To Irun",
  "euskal herri": "Basque Country",
  "euskal herrira": "to Basque Country",
  "bilbora": "To Bilbao",
  "espainiara": "To Spain",
  "europara": "To Europe",
  "frantziara": "To France",
  "gasteizera": "To Vitoria",
  "herrira": "in the country",
  "madrilera": "To Madrid",
  "artean": "between",
  "atzean": "behind",
  "aurrean": "in front (of)",
  "azpian": "under",
  "gainean": "on / over",
  "ondoan": "next to / beside",
  "ezkerrean": "On the left(inessive of ezker)",
  "eskuinean": "On the right(inessive of eskuin)",
  "altuaren": "tall(noren case)",
  "berriaren": "new (noren case)",
  "erlojuen": "watches(noren case) / clocks(noren case)",
  "etxearen": "house(noren case)",
  "gerrikoaren": "belt (Noren case)",
  "gizenaren": "fat (noren case)",
  "gonaen": "skirts(Noren)",
  "gorriaren": "red(noren case)",
  "grisen": "gray (Noren case)",
  "grisetan": "gray(noren case)",
  "handiaren": "big (noren case)",
  "itsusiaren": "ugly (noren case)",
  "jatoraren": "nice (noren case)",
  "larangaren": "orange (noren case)",
  "marroiaren": "brown(noren case)",
  "moreen": "purple(noren case)",
  "poltsaren": "purse(Noren case)",
  "txanoaren": "hat(noren)",
  "txikiaren": "small (noren case)",
  "zuriren": "white (noren case)",
  "zapata": "shoe",
  "alde": "side",
  "ate": "door",
  "leiho": "window",
  "mahai": "table",
  "aulki": "chair",
  "parke": "park",
  "zubi": "bridge",
  "ezker": "left",
  "eskuin": "right",
  "aldean": "side (Noren case)",
  "aldea": "the side",
  "atearen": "door (Noren case)",
  "atea": "the door",
  "aulkiaren": "chair (Noren case)",
  "aulkia": "the chair",
  "kalearen": "street (noren)",
  "leihoa": "the window",
  "leihoen": "windows (Noren case)",
  "mahaiak": "tables",
  "mahaiaren": "table (Noren case)",
  "mahaia": "the table",
  "parkeak": "parks",
  "parkearen": "park (Noren case)",
  "parkea": "the park",
  "zubiak": "bridges",
  "zubiaren": "bridge (Noren case)",
  "zubia": "the bridge",
  "jatetxe": "restaurant",
  "hondartza": "beach",
  "merkatu": "market",
  "plaza": "plaza / square",
  "taberna": "bar / pub",
  "hondartzaren": "beach (noren case)",
  "hotelaren": "hotel (noren case)",
  "jatetxea": "restaurant",
  "jatetxearen": "restaurant (noren case)",
  "merkatua": "market",
  "merkatuaren": "market (noren case)",
  "plazaren": "plaza (noren case) / square (noren case)",
  "tabernaren": "bar (noren case) / pub (noren case)",
  "nengoen": "I was (egon)",
  "zeunden": "You were (egon)",
  "zegoen": "he was / she was / it was",
  "geunden": "We were (egon)",
  "zeundeten": "You (plural) were (egon)",
  "zeuden": "They were (egon)",
  "alemanian": "in Germany",
  "bazegoen": "there was",
  "dirudun": "rich",
  "pobre": "poor",
  "bustia": "wet",
  "lehorra": "dry",
  "garbi": "clean",
  "zikin": "dirty",
  "gose": "hungry",
  "egarri": "thirsty",
  "bustiak": "wet",
  "dirudunak": "rich",
  "diruduna": "rich",
  "egarriak": "thirsty",
  "egarria": "thirsty",
  "garbia": "clean",
  "garbiak": "clean",
  "gosea": "hungry",
  "goseak": "hungry",
  "lehorrak": "dry",
  "pobreak": "poor",
  "pobrea": "poor",
  "zikina": "dirty",
  "zikinak": "dirty",
  "norbait": "somebody",
  "zerbait": "something",
  "inor": "anybody",
  "inor ez": "nobody",
  "denek": "everybody",
  "dena": "everything",
  "ezer ez": "nothing",
  "bero": "hot",
  "hotz": "cold",
  "beltzaren": "black",
  "berdearen": "green",
  "beroa": "hot",
  "hotza": "cold",
  "hotzak": "cold",
  "urdinaren": "blue",
  "alemaniako": "of Germany",
  "bilboko": "of  Bilbao",
  "espainiako": "of Spain",
  "gasteizeko": "from Vitoria",
  "irungo": "of Irun",
  "donostiako": "of San Sebastian",
  "bide": "road",
  "nongoa": "of which place / from which place",
  "alemaniakoak": "of Germany",
  "alemaniakoa": "of Germany",
  "anitza": "Anitza (female name)",
  "anitzaen": "Anitza's (female name, single object)",
  "bilbokoak": "of  Bilbao",
  "bilbokoa": "of  Bilbao",
  "done": "Saint",
  "donostiakoak": "of San Sebastian",
  "donostiakoa": "of San Sebastian",
  "espainiakoak": "of Spain",
  "espainiakoa": "of Spain",
  "espainiera": "Spanish Language",
  "espainieraz": "in Spanish",
  "euskara": "Basque Language",
  "euskaraz": "in Basque",
  "gasteizekoak": "of Vitoria",
  "gasteizekoa": "of Vitoria",
  "herriko": "of the country",
  "ingelesa": "English language",
  "ingeles": "English language",
  "ingelesez": "In English",
  "irunetik": "from Irun",
  "irungoak": "of Irun",
  "irungoa": "of Irun",
  "itziaren": "Itziar's",
  "jakue": "James",
  "olentzero": "Olentzero (Basque Santa)",
  "santa": "Santa",
  "santiagon": "in Santiago",
  "santiagora": "to Santiago",
  "santiago": "Santiago de Compostela (city in Galicia, Spain)",
  "bideaj": "roads",
  "bidea": "road",
  "trena": "train",
  "trenak": "trains",
  "bankuko": "of the bank",
  "dendako": "of the store",
  "elizako": "of the church",
  "eskolako": "of the school",
  "etxeko": "of the house",
  "geltokiko": "of the station",
  "horma": "wall",
  "hoteleko": "of the hotel",
  "teilatu": "roof",
  "aulkiak": "chairs",
  "hormak": "walls",
  "leihoak": "windows",
  "teilatuak": "roofs",
  "teilatua": "roof",
  "mendietako": "of the mountains",
  "dendetako": "of the stores",
  "elizetako": "of the churches",
  "eskoletako": "of the schools",
  "etxeetako": "of the houses",
  "geltokietako": "of the stations",
  "hoteletako": "of the hotels",
  "parketako": "of the parks",
  "gela": "room",
  "ateak": "doors",
  "etxeak": "houses",
  "gelak": "rooms",
  "aspertu": "bored",
  "beldur": "afraid",
  "bizirik": "alive",
  "galdu": "lost",
  "lanpetu": "busy",
  "pozik": "glad / happy",
  "nola": "how",
  "aspertua": "bored",
  "aspertuak": "bored",
  "lanpetua": "busy",
  "zergatik": "why",
  "eserita": "sitting / seated",
  "nekatu": "tired",
  "zutik": "standing",
  "haserre": "angry",
  "gaixo": "sick",
  "kezkatuta": "worried",
  "dirua": "money",
  "dirurik": "any money",
  "olio": "chicken",
  "oiloak": "chickens",
  "nagoelako": "because I am  (egon)",
  "zaudelako": "because you are  (egon)",
  "dagoelako": "because he/she is   (egon)",
  "gaudelako": "because we are  (egon)",
  "zaudetelako": "because you  (plural) are  (egon)",
  "daudelako": "because they are  (egon)",
  "aulkirik": "any chair(s)",
  "gaixorik": "any sickness",
  "irribarre": "smiling",
  "animatuta": "excited",
  "negarrez": "crying",
  "barrez": "laughing",
  "lasai": "relaxed, calm",
  "triste": "sad",
  "hilda": "dead",
  "nengoelako": "because I was (egon)",
  "zeundelako": "because you were (egon)",
  "zegoelako": "because he/she was (egon)",
  "geundelako": "because we were (egon)",
  "zeundetelako": "because you (plural) were (egon)",
  "zeudelako": "because they were (egon)",
  "delako": "because he/she is (izan)",
  "direlako": "because they are (izan)",
  "garelako": "because we are (izan)",
  "naizelako": "because I am (izan)",
  "zarelako": "because you are (izan)",
  "zaretelako": "because you (plural) are (izan)",
  "nintzelako": "because I was",
  "zinelako": "because you were",
  "zelako": "because he/she was",
  "ginelako": "because we were",
  "zinetelako": "because you (plural) were",
  "zirelako": "because they were",
  "guraso": "parent",
  "gurasoa": "parent",
  "eguraldi": "weather",
  "zeru": "sky",
  "eguzki": "sun",
  "eguzkitsu": "sunny",
  "epel": "warm",
  "hodei": "cloud",
  "hodeitsu": "cloudy",
  "hoztu": "cool",
  "eguraldia": "weather",
  "eguzkia": "sun",
  "epela": "warm",
  "etxera": "to a house, to home",
  "hodeia": "cloud",
  "hodeiak": "clouds",
  "hoztua": "cool",
  "zerua": "sky",
  "zeruan": "in the sky",
  "laino": "fog",
  "lainotsu": "foggy",
  "euri": "rain",
  "euritsu": "rainy",
  "elur": "snow",
  "ekaitz": "storm",
  "izoztuta": "frozen",
  "haizetsu": "windy",
  "oso": "very",
  "ekaitza": "storm",
  "elurra": "snow",
  "elurran": "in the snow",
  "euria": "rain",
  "euripean": "in the rain",
  "euritsua": "rainy",
  "haizetsua": "windy",
  "lainoa": "fog",
  "lainotsua": "foggy",
  "lakua": "lake",
  "beraz": "so-so",
  "heze": "humid",
  "hezetasun": "humidity",
  "tenperatura": "temperature",
  "baxua": "low",
  "zentigradu": "centigrade",
  "gradu": "degree",
  "bakarra": "only",
  "eguzkitsua": "sunny",
  "hezea": "humid",
  "hezerik": "any humid",
  "hezetasuna": "humidity",
  "hodeitsua": "cloudy",
  "zentigradua": "centigrade",
  "zentigraduak": "centigrade",
  "hogei": "twenty",
  "hogeita hamar": "thirty",
  "berrogei": "forty",
  "berrogeita hamar": "fifty",
  "hirurogei": "sixty",
  "hirurogeita hamar": "seventy",
  "laurogei": "eighty",
  "laurogeita hamar": "ninety",
  "bider": "times / multiplied by",
  "hogeita": "twenty",
  "berrogeita": "forty",
  "hirurogeita": "sixty",
  "laurogeita": "eighty",
  "bakarrik": "only",
  "gizenak": "fat",
  "merkatuan": "in the market",
  "oilo": "chicken",
  "ehun": "One hundred",
  "berrehun": "Two hundred",
  "hirurehun": "Three hundred",
  "laurehun": "Four hundred",
  "bostehun": "Five hundred",
  "seiehun": "Six hundred",
  "zazpiehun": "Seven hundred",
  "zortziehun": "Eight hundred",
  "bederatziehun": "Nine hundred",
  "leihoan": "in the window",
  "parkean": "in a park",
  "plazan": "in a plaza",
  "urtean": "in a year",
  "mila": "thousand",
  "bi mila": "two thousand",
  "hamar mila": "ten thousand",
  "ehun mila": "one hundred thousand",
  "milioi bat": "one million",
  "hamar milioi": "ten million",
  "ehun milioi": "one hundred million",
  "miliar bat": "one billion",
  "persona": "person",
  "milioi": "million",
  "miliar": "billion",
  "pertsona": "person",
  "urtaro": "Season",
  "udaberria": "Spring",
  "martxoa": "March",
  "apirila": "April",
  "maiatza": "May",
  "hirugarren": "third",
  "laugarren": "fourth",
  "bosgarren": "fifth",
  "hilabete": "month",
  "belarra": "grass",
  "urtaroak": "seasons",
  "hilabetea": "month",
  "hilabeteak": "months",
  "udaberrian": "in the spring",
  "martxoan": "in March",
  "apirilean": "in April",
  "maiatzean": "in May",
  "eguna": "day",
  "urteko": "of the year",
  "uda": "Summer",
  "ekaina": "June",
  "uztaila": "July",
  "abuztua": "August",
  "seigarren": "sixth",
  "zazpigarren": "seventh",
  "zortzigarren": "eighth",
  "ondoren": "after",
  "udaberriaren": "of the spring",
  "ekainaren": "of June",
  "uztailean": "in july",
  "abuztuan": "in August",
  "beroak": "hot",
  "udazkena": "Autumn / Fall",
  "iraila": "September",
  "urria": "October",
  "azaroa": "November",
  "bederatzigarren": "ninth",
  "hamargarren": "tenth",
  "hamaikagarren": "eleventh",
  "hosto": "leaf",
  "udaren": "of summer",
  "abuztuaren": "of August",
  "irailean": "in September",
  "irailaren": "of September",
  "urrian": "in October",
  "urriaren": "of October",
  "azaroan": "in November",
  "hostoa": "leaf",
  "hostoak": "leaves",
  "negua": "Winter",
  "abendua": "December",
  "urtarrila": "January",
  "otsaila": "February",
  "hamabigarren": "twelfth",
  "lehen": "first",
  "bigarren": "second",
  "azken": "last",
  "neguan": "in winter",
  "neguaren": "of winter",
  "abenduan": "in December",
  "abenduaren": "of December",
  "urtarrilean": "in January",
  "otsailean": "in February",
  "lehena": "first",
  "aste": "Week",
  "astelehena": "Monday",
  "asteartea": "Tuesday",
  "asteazkena": "Wednesday",
  "osteguna": "Thursday",
  "ostirala": "Friday",
  "larunbata": "Saturday",
  "igandea": "Sunday",
  "asteko": "of the week",
  "astearen": "of the week",
  "astelehenean": "on Monday",
  "larunbatean": "in/on Saturday",
  "igandean": "on Sunday",
  "nabil": "I am walking",
  "zabiltza": "you are walking",
  "dabil": "he/she/it is walking",
  "gabiltza": "we are walking",
  "zabiltzate": "you (plural) are walking",
  "dabiltza": "they are walking",
  "normalean": "normally / usually",
  "aireportuan": "in the airport",
  "geltokian": "in the station",
  "hondartzan": "on the beach",
  "zubian": "on the bridge",
  "nenbilen": "I was walking",
  "zenbiltzan": "You were walking",
  "zebilen": "He/she was walking",
  "genbiltzan": "We  were walking",
  "zenbiltzaten": "You (plural) were walking",
  "asteartean": "on Tuesday",
  "asteazkenean": "on Wednesday",
  "ostegunean": "on Thursday",
  "ostiralean": "on Friday",
  "zebiltzan": "They were walking",
  "autobusez": "by bus",
  "trenez": "by train",
  "ferry": "ferry",
  "ferryz": "by ferry",
  "hegazkin": "airplane",
  "hegazkinez": "by airplane",
  "kamioi": "truck",
  "kamioiz": "by truck",
  "motor": "motorcycle",
  "motorrez": "by motorcycle",
  "ekainean": "in June",
  "astero": "every week",
  "igandero": "every Sunday",
  "dendetara": "to the stores",
  "eskolara": "to school",
  "ferrya": "the ferry",
  "hegazkina": "the airplane",
  "egin": "was made / do (command) / did",
  "egiten": "do / is made / doing",
  "egingo": "will do / will be made",
  "esku": "hand",
  "eskuz": "by hand",
  "oin": "foot",
  "oinez": "on foot",
  "bizikletaz": "by bicycle",
  "taxi": "taxi",
  "taxiz": "by taxi",
  "zaldiz": "on horseback, by horse",
  "eskua": "hand",
  "eskuak": "hands",
  "jertseak": "sweaters",
  "makina": "machine",
  "oina": "foot",
  "oinak": "feet",
  "parkera": "to the park",
  "taxiak": "taxis",
  "taxia": "taxi",
  "makinaz": "by machine",
  "gauez": "at night",
  "hizkuntza": "language",
  "seinale": "sign",
  "hizkuntzak": "languages",
  "makinak": "machines",
  "seinalea": "sign",
  "seinaleak": "signs",
  "denbora": "time",
  "ordu": "hour",
  "minutu": "minute",
  "laster": "soon",
  "oraindik": "still/yet",
  "ordu bata": "one o’clock",
  "ordu biak": "two o’clock",
  "hirurak": "three o'clock",
  "laurak": "four o'clock",
  "bostak": "five o'clock",
  "seiak": "six o'clock",
  "erdia": "half",
  "laurdena": "quarter",
  "dagoeneko": "already",
  "bata": "one o'clock",
  "biak": "two o'clock",
  "erdiak": "half",
  "erdietan": "at half",
  "laurdenak": "quarter",
  "zazpiak": "seven o'clock",
  "zortziak": "eight o'clock",
  "bederatziak": "nine o'clock",
  "hamarrak": "ten o'clock",
  "hamaikak": "eleven o'clock",
  "hamabiak": "twelve o'clock",
  "eguerdia": "noon",
  "gauerdi": "midnight",
  "gaur gauean": "tonight",
  "hamabostetan": "at fifteen",
  "eguerdian": "at noon",
  "gauerdia": "midnight",
  "gauerdian": "at midnight",
  "gauean": "at night",
  "ekarri": "bring (command) / brought",
  "gelditu": "stopped / stop (command)",
  "hitz egin": "speak",
  "idatzi": "write (command) / wrote",
  "hona": "to here",
  "izen": "name",
  "aulkian": "on the chair",
  "hitz": "word / speak",
  "izena": "name",
  "izenak": "names",
  "mahaian": "on the table",
  "igo": "climb / ascend / go up",
  "jaitsi": "descend/go down",
  "irakurri": "read (command) / read (past)",
  "isildu": "quiet",
  "itxaron": "wait",
  "sartu": "enter (command)",
  "kontuz": "careful (command)",
  "utzi": "drop (command) / release (command) / let (command) / leave (command)",
  "gelara": "to the room",
  "menditik": "from the mountain",
  "zuhaitzetik": "down, from the tree",
  "zuhaitzera": "to, up the tree",
  "eskuinera": "to the right",
  "ezkerrera": "to the left",
  "biratu": "turn",
  "zuzen": "straight",
  "gertu": "near",
  "toilet": "komun",
  "behean": "downstairs",
  "goian": "upstairs",
  "hartu": "took / take (command)",
  "komun": "bathroom / toilet",
  "komuna": "bathroom / toilet",
  "izkina": "corner",
  "pasa": "pass",
  "kilometro": "kilometer",
  "metro": "meter",
  "semaforo": "stoplight / traffic light",
  "urrun": "far",
  "bankua": "bank",
  "hemendik": "from here",
  "hondartzatik": "from the beach",
  "kilometrora": "kilometer (NORA case)",
  "merkatutik": "from the market",
  "izkinan": "at the corner",
  "semaforoa": "stoplight / traffic light",
  "semaforoan": "at the stoplight / at the traffic light",
  "zubitik": "from the bridge",
  "ahal izan": "could",
  "behar izan": "had to",
  "ezin": "not able to / could not / couldn't",
  "azken urtean": "last year",
  "azken hilabetean": "last month",
  "paris": "Paris",
  "parisen": "in Paris",
  "hilabetean": "month (in a)",
  "astea": "a week",
  "ahal": "able to / could / can",
  "behar": "must / have to / had to",
  "hondartzara": "to the beach",
  "izan": "2d part of some compound verbs",
  "plazaen": "to the plaza",
  "kotxez": "by car",
  "ahal izango": "will be able to",
  "beharko": "future of behar",
  "izango": "future of izan",
  "merkatura": "to the market",
  "tabernara": "to the bar / to the pub",
  "niri": "to me",
  "hari": "to him/her/it",
  "guri": "to us",
  "haiei": "to them",
  "entzun": "listen (command) / heard / listened to",
  "menu": "menu",
  "menua": "menu",
  "zuei": "to you (plural)",
  "anitzari": "to Anitza",
  "josebari": "to Joseba",
  "mikeli": "to Mikel",
  "mireni": "to Miren",
  "ikasle bati": "to a student",
  "irakasle bati": "to a teacher",
  "lagun bati": "to a friend",
  "mutil bati": "to a boy",
  "eman": "give",
  "espainiar": "Spanish",
  "bati": "to a",
  "irakasleari": "to the teacher",
  "amari": "to the mother",
  "neskari": "to the girl",
  "irakasleei": "to the teachers",
  "amei": "to the mothers",
  "neskei": "to the girls",
  "apaizei": "to priests",
  "emakumeari": "to the woman",
  "erizainei": "to the nurses",
  "gidariari": "to the driver",
  "gizonari": "to the man",
  "ikasleei": "to students",
  "medikuei": "to the doctors",
  "mutikoari": "to the boy",
  "pertsonei": "to persons / to people",
  "poliziei": "to the police officers",
  "sukaldariekin": "to the cooks",
  "turistei": "to the tourists",
  "zait": "it is to me",
  "zaizu": "it is to you",
  "zaio": "it is to him/her/it",
  "zaigu": "it is to us",
  "zaizue": "it is to you (plural)",
  "zaie": "it is to them",
  "gustatuko": "will like (will be pleasing)",
  "gustatzen": "like (is pleasing)",
  "gustatu": "liked (was pleasing)",
  "zaizkit": "they are to me",
  "zaizkizu": "they are to you",
  "zaizkio": "they are to him/her/it",
  "zaizkigu": "they are to us",
  "zaizkizue": "they are to you(plural)",
  "zaizkie": "they are to them",
  "interesatu": "was interesting to",
  "interesatzen": "is interesting to",
  "interesatuko": "will be interesting to",
  "geltokiak": "stations",
  "hegazkinak": "airplanes",
  "kamioiak": "trucks",
  "motorrak": "motorcycles",
  "zineak": "cinemas / movie theaters",
  "berdin izan": "was the same",
  "berdin izango": "will be the same",
  "kostatu": "cost",
  "kostatzen": "costs",
  "kostatuko": "will cost",
  "iruditu": "seemed",
  "iruditzen": "seems",
  "irudituko": "will seem",
  "gelditen": "remains, is left",
  "geldituko": "will stop",
  "ardo": "wine",
  "gutxi": "little (amount) / few",
  "dut": "I have/ukan it",
  "duzu": "You have/ukan it",
  "du": "He/she/it has/ukan it",
  "dugu": "We have/ukan it",
  "duzue": "You (plural) have/ukan  it",
  "dute": "They have/ukan it",
  "ireki": "opened",
  "itxi": "closed",
  "jaso": "received",
  "garbitu": "cleaned",
  "anitzak": "Anitza",
  "josebak": "Joseba",
  "mikelek": "Mikel",
  "mirenek": "Miren",
  "amek": "mother",
  "autobusik": "any bus",
  "batek": "one",
  "bizikletarik": "any bicycles",
  "camareroek": "waiters",
  "daukagu": "We have it",
  "dauka": "He/she/it has it",
  "daukate": "They have it",
  "daukat": "I have it",
  "daukazue": "You (plural) have it",
  "dauzkat": "I have them",
  "dauzkazu": "You have them",
  "dauzka": "He/she/it has them",
  "dauzkagu": "We have them",
  "dauzkazue": "You (plural) have them",
  "dauzkate": "They have them",
  "daukazu": "You have it",
  "diru": "money",
  "dortokarik": "any turtles",
  "elizak": "churches",
  "emakumeek": "women",
  "erlojurik": "a watch / any watches / a clock / any clocks",
  "etxekoandreek": "housewives",
  "geneukan": "We had it",
  "geneuzkan": "We had them",
  "gizonek": "men",
  "guk": "we",
  "hark": "he, she, it",
  "neskek": "girl",
  "neukan": "I had it",
  "neuzkan": "I had them",
  "nik": "I",
  "poltsarik": "any purses",
  "txakurrik": "any dogs",
  "txerriek": "pig",
  "zaldirik": "any horse",
  "zeneukan": "You had it",
  "zeneukaten": "You (plural) had it",
  "zeneuzkan": "You had them",
  "zeneuzkaten": "You (plural) had them",
  "zeukan": "He/she/it had it",
  "zeukaten": "They had it",
  "zeuzkan": "He/she/it had them",
  "zeuzkaten": "They had them",
  "zuk": "you",
  "irekitzen": "open",
  "ixten": "close",
  "jasotzen": "receive",
  "garbitzen": "clean",
  "geltokia": "the station",
  "jertserik": "a sweater / any sweater",
  "irekiko": "will open",
  "itxiko": "will close",
  "jasoko": "will receive",
  "garbituko": "will clean",
  "datorren": "next",
  "ditut": "I have them",
  "dituzu": "You have them",
  "ditu": "He/she/it has them",
  "ditugu": "We have them",
  "dituzue": "You (plural) have them",
  "dituzte": "They have them",
  "ikusi": "saw",
  "egosi": "cooked",
  "jan": "ate",
  "egunkari": "newspaper",
  "batzuk": "a few",
  "egosten": "cook (present)",
  "egunkariak": "newspapers",
  "egunkaria": "newspaper",
  "ikusten": "see",
  "irakurtzen": "read (present)",
  "jaten": "eat (present)",
  "medikuek": "doctors",
  "apaizek": "priests",
  "gidariek": "drivers",
  "irakurriko": "will read",
  "ikusiko": "will see",
  "egostiko": "will cook",
  "jango": "will eat",
  "datorren hilabetean": "Next month",
  "txakurrek": "dogs",
  "abestu": "sang",
  "aldatu": "changed",
  "erabili": "used",
  "abesti": "song",
  "abesten": "sing",
  "abestia": "song",
  "abestiak": "songs",
  "abestirik": "any  songs",
  "aldatzen": "change",
  "ekartzen": "bring",
  "entzuten": "hear / listen to",
  "erabiltzen": "use",
  "idazten": "write / writing",
  "aiton-amonek": "grandparents",
  "behiek": "cows",
  "denborak": "times",
  "abestuko": "will sing",
  "aldatuko": "will change",
  "ekarriko": "will bring",
  "erabiliko": "will use",
  "idatziko": "will write",
  "entzungo": "will hear / will listen to",
  "menuak": "menus",
  "mutillagunak": "boyfriend(s)",
  "mutillagunek": "boyfriends",
  "neskalagunek": "girlfriends",
  "senarrak": "husbands",
  "irakatsi": "taught",
  "eraman": "carried",
  "esan": "said",
  "hil": "killed",
  "alemana": "German",
  "alemanez": "in German",
  "frantsesa": "French",
  "frantsesez": "in French",
  "ahizpek": "sisters",
  "arrebaek": "sisters",
  "eramaten": "carry",
  "ermango": "will carry",
  "esango": "will say",
  "esaten": "say",
  "gelditzen": "stop",
  "hartuko": "will take",
  "hartzen": "take",
  "hiltzen": "kill",
  "hilko": "will kill",
  "irakasten": "teach",
  "irakatsiko": "will teach",
  "lehengusuek": "cousins",
  "lehengusuaek": "cousins",
  "eramango": "will carry",
  "izebek": "aunts",
  "nuen": "I had it",
  "zenuen": "You had it",
  "genuen": "We had it",
  "zenuten": "You (plural) had it",
  "zuten": "They had it",
  "azken astean": "Last week",
  "ahuntzek": "goats",
  "genituen": "We had them",
  "hilean": "month",
  "nituen": "I had them",
  "zenituen": "You had them",
  "zenituzten": "You (plural) had them",
  "zituen": "he had them / she had them / it had them",
  "zituzten": "They had them",
  "erizainek": "nurses",
  "motora": "motorcycle",
  "barre": "laugh",
  "bisita": "visit",
  "dantza": "dance",
  "eztul": "cough",
  "hots": "call",
  "korri": "run",
  "kosk": "bite",
  "lan": "work",
  "lo": "sleep",
  "negar": "cry/weep",
  "oihu": "shout",
  "amets": "dream",
  "erdara": "a foreign language (usually a language other than Basque, French or Spanish)",
  "erdaraz": "in erdara",
  "motorra": "motorcycle",
  "haiek zeuzkaten": "They had them",
  "dakit": "I know it",
  "dakizu": "you know it",
  "daki": "he/she knows it",
  "dakigu": "we know it",
  "dakizue": "you (plural) know it",
  "dakite": "they know it",
  "gidatzen": "to drive",
  "ainhoa": "Ainhoa",
  "badakigu": "we know it",
  "badaki": "he/she knows it",
  "badakite": "they know it",
  "badakizkigu": "We know them",
  "badakizki": "He/she knows them",
  "badakizkite": "They know them",
  "badakizkit": "I know them",
  "badakizkizue": "You (plural) know them",
  "badakizkizu": "You know them",
  "badakizue": "you (plural) know it",
  "badakizu": "you know it",
  "bagenekien": "We knew it",
  "bagenekizkien": "We knew them",
  "bagidatzen": "to drive",
  "banekien": "I knew it",
  "banekizkien": "I knew them",
  "bazekien": "He/she knew it",
  "bazekiten": "They knew it",
  "bazekizkien": "He/she knew them",
  "bazekizkiten": "They knew them",
  "bazenekien": "You knew it",
  "bazenekiten": "You (plural) knew it",
  "bazenekizkien": "You knew them",
  "bazenekizkiten": "You (plural) knew them",
  "dakizkigu": "We know them",
  "dakizki": "He/she knows them",
  "dakizkite": "They know them",
  "dakizkit": "I know them",
  "dakizkizue": "You (plural) know them",
  "dakizkizu": "You know them",
  "genekien": "We knew it",
  "genekizkien": "We knew them",
  "ikasleen": "students'",
  "nekien": "I knew it",
  "nekizkien": "I knew them",
  "zekien": "He/she knew it",
  "zekiten": "They knew it",
  "zekizkien": "He/she knew them",
  "zekizkiten": "They knew them",
  "zenekien": "You knew it",
  "zenekiten": "You (plural) knew it",
  "zenekizkien": "You knew them",
  "zenekizkiten": "You (plural) knew them",
  "badakit": "I know it",
  "dantzan": "to dance",
  "sugeek": "snakes",
  "dantzatzen": "dance",
  "sukaldatzen": "to cook",
  "mutilek": "boys",
  "sugearen": "snake's",
  "turistek": "tourists",
  "apaizen": "of the priests",
  "emakumeen": "of the women",
  "irakasleen": "of the teachers",
  "txakurren": "of the dogs",
  "zaldiek": "horses",
  "kantatzen": "singing",
  "ari": "present perfect verb form",
  "hodeietatik": "from the clouds",
  "jostatzen": "playing",
  "laguntzen": "helping",
  "joko": "game",
  "batera": "a",
  "ahuntzei": "to the goats(dative)",
  "jolasten": "playing",
  "turistari": "to the tourist (dative)",
  "irten": "departing",
  "itxaroten": "waiting",
  "irteten": "departing",
  "itxaoten": "waiting",
  "kotxean": "in the car",
  "norekin": "With whom",
  "zerekin": "With what",
  "mirenekin": "With Miren",
  "mikeleking": "With Mikel",
  "boligrafoarekin": "With a pen",
  "batekin": "With one",
  "baloiarekin": "With a ball",
  "txakurrarekin": "With a dog",
  "mikelekin": "With Mikel",
  "dantzatu": "dance",
  "lagunarekin": "With the friend",
  "irakaslearekin": "With the teacher",
  "ahizparekin": "With the sister of a sister",
  "arrebarekin": "With the sister of a brother",
  "nebarekin": "With the brother of a sister",
  "anaiarekin": "with the brother of a brother",
  "lagunekin": "With the friends",
  "betaurrekoekin": "With the glasses",
  "baloiekin": "With the balls",
  "boligrafoekin": "With the pens",
  "arkatzekin": "With the pencils",
  "ikasleek": "students",
  "abeste": "to sing",
  "egote": "being at a place",
  "erortze": "falling",
  "eserte": "to sit",
  "esnatze": "to wake up",
  "ibiltze": "walking",
  "iriste": "to arrive",
  "irte": "to depart",
  "itxaote": "to wait",
  "batetik": "from a",
  "abestea": "to sing",
  "behiei": "cows",
  "egotea": "being at a place",
  "erortzea": "falling",
  "esnatzea": "to wake up",
  "esertze": "sitting",
  "esertzea": "sitting",
  "ibiltzea": "walking",
  "iristea": "to arrive",
  "itxarotea": "waiting",
  "bizitzea": "to live",
  "entzutea": "to listen",
  "musika": "music",
  "garbitzea": "to clean",
  "gelditzea": "to stop",
  "idaztea": "to write",
  "dantzatzea": "to dance",
  "jotzea": "to play",
  "egitea": "to be doing something",
  "hontzei": "owls",
  "katuei": "cats",
  "mutilei": "boys",
  "txerriei": "pigs",
  "zitzaidan": "I was (izan)",
  "zitzaizun": "you were (izan)",
  "zitzaion": "he/she/it was (izan)",
  "zitzaigun": "we were (izan)",
  "zitzaizuen": "you (plural) were (izan)",
  "zitzaien": "they were (izan)",
  "ikastera": "to learn",
  "ikustera": "to see",
  "erostea": "to buy",
  "ogi": "bread",
  "laguntzera": "to help",
  "hiltzera": "to kill",
  "jolastera": "to play",
  "irakastera": "to teach",
  "ixtera": "to close",
  "gaztelania": "to go to (teach) Spanish",
  "autobusera": "to the bus",
  "barrura": "to go inside",
  "erostera": "go to buy",
  "kanpora": "to go outside",
  "lagunari": "to go to a friend",
  "ogia": "bread",
  "nahi izan": "wanted",
  "banana": "banana",
  "limoi": "lemon",
  "madari": "pear",
  "sandia": "watermelon",
  "melokotoi": "peach",
  "anaiek": "brothers of a brother",
  "arraultz": "egg",
  "azenario": "carrot",
  "egiteko": "in order to make/do",
  "erosteko": "in order to buy",
  "idazteko": "in order to write",
  "ikasteko": "in order to learn",
  "irakurtzeko": "in order to read",
  "jateko": "in order to eat",
  "joateko": "in order to go",
  "limoia": "lemon",
  "limoiak": "lemons",
  "madaria": "pear",
  "madariak": "pears",
  "marrubi": "strawberry",
  "melokotoia": "peach",
  "melokotoiak": "peaches",
  "nahiko": "will want",
  "nahi": "want",
  "ogitarteko": "sandwich",
  "patata": "potato",
  "pizza": "pizza",
  "sagar": "apple",
  "sandiak": "watermelons",
  "tipula": "onion",
  "tomate": "tomato",
  "txistorra": "sausage",
  "arrautz": "egg",
  "arrautza": "egg",
  "arrautzak": "eggs",
  "azenarioak": "carrots",
  "ogitartekoak": "sandwiches",
  "pizzas": "pizzak",
  "tipulak": "onions",
  "tomateak": "tomatoes",
  "hemezortzi": "eighteen",
  "marrubia": "strawberry",
  "marrubiak": "strawberries",
  "neskalagunak": "girlfriend(s)",
  "patatak": "potatoes",
  "sagara": "apple",
  "sagarrak": "apples",
  "txistorrak": "sausages",
  "euskeraz": "basque",
  "korrika": "to run",
  "edan": "drank",
  "botila": "bottle",
  "garagardo": "beer",
  "ur": "water",
  "freskagarri": "soft drink/soda/ soda pop",
  "bart": "last night",
  "ardoa": "wine",
  "ardoak": "wines",
  "ardorik": "any wine",
  "basoak": "glasses",
  "botilak": "bottles",
  "edango": "will drink",
  "edaten": "drinking",
  "esne": "milk",
  "esnea": "milk",
  "esneak": "milks",
  "freskagarria": "soft drink/soda/ soda pop",
  "freskagarriak": "soft drinks/sodas/ soda pops",
  "freskagarririk": "any soft drinks/ sodas/soda pops",
  "garagardoa": "beer",
  "garagardoak": "beers",
  "gelan": "in the room",
  "kafea": "coffee",
  "kafeak": "coffees",
  "kafe": "coffee",
  "kopa": "cup",
  "kopak": "cups",
  "sagardoa": "apple cider",
  "sagardoak": "apple ciders",
  "sagardo": "apple cider",
  "te": "tea",
  "tea": "tea",
  "teak": "teas",
  "ura": "water",
  "zuku": "juice",
  "zukua": "juice",
  "zukuak": "juices",
  "goizero": "every morning",
  "arroz": "rice",
  "gazta": "cheese",
  "izozki": "ice cream",
  "afaldu": "had dinner",
  "afalduko": "will have dinner",
  "afaltzen": "having dinner",
  "afari": "dinner",
  "arrozak": "rices",
  "arroza": "rice",
  "artoa": "corn",
  "artoak": "corns",
  "azukrea": "sugar",
  "azukreak": "sugars",
  "azukre": "sugar",
  "babarruna": "bean",
  "babarrunak": "beans",
  "babarrun": "bean",
  "barazkiak": "vegetables",
  "barazkia": "vegetable",
  "barazki": "vegetable",
  "bazkaldu": "had lunch",
  "bazkalduko": "will have lunch",
  "bazkaltzen": "having lunch",
  "bazkari": "lunch",
  "entsaladak": "salads",
  "entsalada": "salad",
  "fruta": "fruit",
  "frutak": "fruits",
  "gatzak": "salts",
  "gatza": "salt",
  "gatzia": "salty",
  "gatzi": "salty",
  "gatz": "salt",
  "gazia": "sour",
  "gazi": "sour",
  "gaztak": "cheeses",
  "gosaldu": "ate breakfast",
  "gosalduko": "will eat breakfast",
  "gosaltzen": "eat breakfast",
  "gosari": "breakfast",
  "gozoa": "sweet",
  "haragiak": "meats",
  "haragia": "meat",
  "haragi": "meat",
  "izozkia": "ice cream",
  "izozkiak": "ice creams",
  "letxugak": "lettuces",
  "letxuga": "lettuce",
  "mahatsa": "grape",
  "mahatsak": "grapes",
  "mahats": "grape",
  "mina": "spicy",
  "ozpinak": "vinegars",
  "ozpina": "vinegar",
  "pintxoak": "tapas",
  "pintxo": "tapa",
  "piperak": "peppers",
  "pipera": "pepper",
  "piper": "pepper",
  "prest": "ready",
  "sukaldariek": "cooks",
  "txerrikia": "pork",
  "txerriki": "pork",
  "txuletak": "steaks",
  "txuleta": "steak",
  "zopak": "soups",
  "zopa": "soup",
  "artorik": "any corn",
  "entsaladako": "in the salad",
  "haragirik": "any meat",
  "tomaterik": "any tomatoes",
  "afaltzeko": "for dinner",
  "bazkaltzeko": "for lunch",
  "fruituak": "fruit",
  "gosaria": "breakfast",
  "gosaltzeko": "for breakfast",
  "jatetxean": "in a restaurant",
  "hamabietan": "at twelve",
  "afaria": "dinner",
  "bazkaria": "lunch",
  "irakasleek": "teachers",
  "garratza": "sour",
  "garratzak": "sour",
  "gozoak": "sweet",
  "piperrak": "peppers",
  "piperra": "pepper",
  "txuletarako": "for the steak",
};

function renderPromptWords(sentence: string) {
  const words = sentence.split(/(\s+)/);
  return words.map((word, idx) => {
    if (word.trim() === "") {
      return <span key={idx}>{word}</span>;
    }

    const cleanWord = word.replace(/^[.,\/#!$%\^&\*;:{}=\-_`~()?]+|[.,\/#!$%\^&\*;:{}=\-_`~()?]+$/g, "");
    const leadingPunc = word.substring(0, word.indexOf(cleanWord));
    const trailingPunc = word.substring(word.indexOf(cleanWord) + cleanWord.length);

    const lookup = cleanWord.toLowerCase();
    const translation = BASQUE_TO_ENGLISH[lookup];

    if (translation) {
      return (
        <span key={idx} className="inline-block">
          {leadingPunc}
          <span className="relative group inline-block cursor-help border-b-2 border-dotted border-[#afafaf] hover:border-duo-blue dark:border-[#4b4b4b] dark:hover:border-duo-blue pb-0.5 select-none">
            {cleanWord}
            {/* Tooltip */}
            <span className="invisible opacity-0 group-hover:visible group-hover:opacity-100 transition-all duration-200 absolute left-1/2 -translate-x-1/2 bottom-full mb-2.5 bg-gray-800 text-white text-xs py-1.5 px-3 rounded-lg shadow-lg whitespace-nowrap z-50 dark:bg-gray-100 dark:text-gray-900 font-bold tracking-normal leading-normal">
              {translation}
              {/* Tooltip arrow */}
              <span className="absolute top-full left-1/2 -translate-x-1/2 w-0 h-0 border-t-[5px] border-t-gray-800 border-x-[5px] border-x-transparent dark:border-t-gray-100" />
            </span>
          </span>
          {trailingPunc}
        </span>
      );
    }

    return <span key={idx}>{word}</span>;
  });
}

export function TranslateChallenge({
  question,
  prompt,
  audioText,
  grammarTip,
  options,
  selectedTokens,
  onSelectToken,
  onRemoveToken,
  setSelectedTokens,
  isKeyboardMode,
  status,
}: TranslateChallengeProps) {
  const [typedBuffer, setTypedBuffer] = useState("");
  const [keyboardText, setKeyboardText] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const isSelected = (id: number) => selectedTokens.some((t) => t.id === id);

  // Parse question to extract quoted prompt and clean the header question
  let displayQuestion = question;
  let displayPrompt = prompt;

  const quoteMatch = question.match(/["']([^"']+)["']/);
  if (quoteMatch) {
    displayPrompt = quoteMatch[1];
    const basqueWords = ["eta", "on", "kaixo", "agur", "egun", "arratsalde", "gabon", "mesedez", "eskerrik", "asko", "zer", "duzu"];
    const isTargetBasque = options.some(opt =>
      basqueWords.includes(opt.text.toLowerCase().trim())
    );
    displayQuestion = isTargetBasque ? "Write this in Basque" : "Write this in English";
  }

  // Focus textarea when in keyboard mode and challenge or mode changes
  useEffect(() => {
    if (isKeyboardMode && status === "idle" && textareaRef.current) {
      textareaRef.current.focus();
    }
  }, [isKeyboardMode, question, status]);

  // Reset inputs when challenge changes
  useEffect(() => {
    setKeyboardText("");
  }, [question]);

  // Clear typed buffer when status or options change
  useEffect(() => {
    setTypedBuffer("");
  }, [status, options]);

  // Keyboard handler for typing word first letters (Word Bank mode only)
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (status !== "idle" || isKeyboardMode) return;

      const activeEl = document.activeElement;
      if (
        activeEl &&
        (activeEl.tagName === "INPUT" ||
          activeEl.tagName === "TEXTAREA" ||
          (activeEl as HTMLElement).isContentEditable)
      ) {
        return;
      }

      // Backspace: remove buffer character or last selected token
      if (e.key === "Backspace") {
        if (typedBuffer.length > 0) {
          e.preventDefault();
          setTypedBuffer((prev) => prev.slice(0, -1));
        } else if (selectedTokens.length > 0) {
          e.preventDefault();
          const lastToken = selectedTokens[selectedTokens.length - 1];
          sound.playClick();
          onRemoveToken(lastToken);
        }
        return;
      }

      // Space / Enter: select first matched token from buffer
      if (e.key === " " || e.key === "Enter") {
        if (typedBuffer.length > 0) {
          e.preventDefault();
          const match = options.find((opt) => {
            if (isSelected(opt.id)) return false;
            const norm = normalizeWord(opt.text);
            return norm.startsWith(typedBuffer.toLowerCase());
          });
          if (match) {
            sound.playClick();
            onSelectToken(match);
            setTypedBuffer("");
          }
        }
        return;
      }

      // Escape: clear typed buffer
      if (e.key === "Escape") {
        setTypedBuffer("");
        return;
      }

      // Single character typing (letters, numbers, etc.)
      if (e.key.length === 1 && !e.ctrlKey && !e.metaKey && !e.altKey) {
        const char = e.key.toLowerCase();
        const newBuf = typedBuffer + char;

        // Find available candidate matching new buffer
        const candidate = options.find((opt) => {
          if (isSelected(opt.id)) return false;
          const norm = normalizeWord(opt.text);
          return norm.startsWith(newBuf);
        });

        if (candidate) {
          e.preventDefault();
          // Check if only one candidate matches or exact match
          const matchingCandidates = options.filter((opt) => {
            if (isSelected(opt.id)) return false;
            const norm = normalizeWord(opt.text);
            return norm.startsWith(newBuf);
          });

          if (matchingCandidates.length === 1 && normalizeWord(matchingCandidates[0].text) === newBuf) {
            sound.playClick();
            onSelectToken(matchingCandidates[0]);
            setTypedBuffer("");
          } else {
            setTypedBuffer(newBuf);
          }
        } else {
          // Check if single char starts any token
          const singleMatch = options.find((opt) => {
            if (isSelected(opt.id)) return false;
            const norm = normalizeWord(opt.text);
            return norm.startsWith(char);
          });
          if (singleMatch) {
            e.preventDefault();
            setTypedBuffer(char);
          }
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [status, typedBuffer, options, selectedTokens, onSelectToken, onRemoveToken, isKeyboardMode]);

  return (
    <div className="flex w-full max-w-2xl flex-col items-center">
      {/* Question Title */}
      <h2 className="text-2xl md:text-3xl font-black text-[#3c3c3c] text-center dark:text-white">
        {displayQuestion}
      </h2>

      {/* Prompt / Audio Bubble with Mascot */}
      {(displayPrompt || audioText) && (
        <div className="mt-6 flex items-center gap-4 w-full justify-center max-w-lg">
          {/* Mascot (Little Euskara Bird) */}
          <div className="h-24 w-24 md:h-28 md:w-28 shrink-0 relative">
            <img
              src="/mascot.svg"
              alt="Hitzak Bird"
              className="h-full w-full object-contain"
            />
          </div>

          {/* Speech Bubble */}
          <div className="relative flex-1 flex items-center gap-3 rounded-2xl border-2 border-duo-gray-border bg-white p-4 shadow-sm dark:border-[#37464f] dark:bg-[#182c34]">
            {/* Left triangle pointer for speech bubble */}
            <div className="absolute top-1/2 -left-3.5 -translate-y-1/2 w-0 h-0 border-y-8 border-y-transparent border-r-8 border-r-duo-gray-border dark:border-r-[#37464f]">
              <div className="absolute -top-[8px] left-[2px] w-0 h-0 border-y-[8px] border-y-transparent border-r-[8px] border-r-white dark:border-r-[#182c34]" />
            </div>


            {displayPrompt && (
              <span className="text-lg font-black text-[#3c3c3c] dark:text-white leading-tight">
                {displayQuestion === "Write this in English" ||
                  displayQuestion.toLowerCase() === "translate this sentence:" ||
                  displayQuestion.toLowerCase().includes("into english")
                  ? renderPromptWords(displayPrompt)
                  : displayPrompt}
              </span>
            )}
          </div>
        </div>
      )}

      {isKeyboardMode ? (
        /* Keyboard Input Area */
        <div className="mt-8 w-full">
          <textarea
            ref={textareaRef}
            value={keyboardText}
            onChange={(e) => {
              const val = e.target.value;
              setKeyboardText(val);
              const words = val.split(/\s+/).filter(Boolean).map(w =>
                w.replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?]/g, "").trim()
              ).filter(Boolean);
              const mockTokens = words.map((word, idx) => ({
                id: -idx - 1,
                text: word,
                correct: true,
              }));
              setSelectedTokens(mockTokens);
            }}
            disabled={status !== "idle"}
            placeholder={displayQuestion === "Write this in Basque" ? "Type in Basque" : "Type in English"}
            className="w-full p-4 h-36 rounded-2xl border-2 border-duo-gray-border bg-gray-50 focus:outline-none focus:border-duo-blue resize-none font-medium text-lg text-[#3c3c3c] dark:border-[#37464f] dark:bg-[#182c34] dark:text-white dark:focus:border-duo-blue transition-all"
          />
        </div>
      ) : (
        /* Word Bank Mode */
        <>
          {/* Answer Slots Line */}
          <div className="mt-8 flex min-h-16 w-full flex-wrap items-center gap-2.5 rounded-2xl border-b-2 border-dashed border-duo-gray-dark/40 bg-gray-50/50 p-4 dark:border-[#37464f] dark:bg-[#131f24]/60">
            {selectedTokens.length === 0 ? (
              <span className="text-sm font-bold text-gray-400 dark:text-gray-500">
              </span>
            ) : (
              selectedTokens.map((token) => (
                <button
                  key={token.id}
                  onClick={() => {
                    if (status === "idle") {
                      sound.playClick();
                      onRemoveToken(token);
                    }
                  }}
                  disabled={status !== "idle"}
                  className={cn(
                    "rounded-xl border-2 px-4 py-2.5 text-base font-black transition-all select-none",
                    status === "idle" && "border-duo-gray-border bg-white text-[#4b4b4b] shadow-3d-gray hover:bg-gray-50 active:translate-y-1 dark:border-[#37464f] dark:bg-[#182c34] dark:text-white",
                    status === "correct" && "border-duo-green bg-duo-green-light text-duo-green-dark shadow-3d-green dark:border-emerald-500 dark:bg-emerald-950/60 dark:text-emerald-300",
                    status === "wrong" && "border-duo-red bg-duo-red-light text-duo-red-dark shadow-3d-red dark:border-red-500 dark:bg-red-950/60 dark:text-red-300"
                  )}
                >
                  {token.text}
                </button>
              ))
            )}
          </div>

          {/* Word Bank Pool */}
          <div className="mt-8 flex flex-wrap justify-center gap-3 w-full">
            {options.map((option) => {
              const used = isSelected(option.id);
              const normalized = normalizeWord(option.text);
              const isMatchingPrefix =
                !used &&
                typedBuffer.length > 0 &&
                normalized.startsWith(typedBuffer.toLowerCase());
              const isFilteredOut =
                !used && typedBuffer.length > 0 && !isMatchingPrefix;

              return (
                <button
                  key={option.id}
                  onClick={() => {
                    if (status === "idle" && !used) {
                      sound.playClick();
                      onSelectToken(option);
                      setTypedBuffer("");
                    }
                  }}
                  disabled={used || status !== "idle"}
                  className={cn(
                    "rounded-xl border-2 px-4 py-2.5 text-base font-black transition-all relative select-none",
                    used &&
                    "border-transparent bg-gray-200/60 text-transparent shadow-none cursor-default dark:bg-[#182c34]/30",
                    !used &&
                    !isMatchingPrefix &&
                    !isFilteredOut &&
                    "border-duo-gray-border bg-white text-[#4b4b4b] shadow-3d-gray hover:bg-gray-50 active:translate-y-1 active:shadow-3d-gray-pressed dark:border-[#37464f] dark:bg-[#182c34] dark:text-[#f7f7f7] dark:hover:bg-[#203a45]",
                    !used &&
                    isMatchingPrefix &&
                    "border-[#84d8ff] bg-[#ddf4ff] text-[#1899d6] shadow-3d-blue scale-105 ring-2 ring-duo-blue/30 dark:border-[#1899d6] dark:bg-[#1899d6]/20 dark:text-[#1cb0f6]",
                    !used &&
                    isFilteredOut &&
                    "border-duo-gray-border bg-gray-100/70 text-[#9e9e9e] opacity-40 shadow-none dark:border-[#37464f] dark:bg-[#131f24] dark:text-gray-600"
                  )}
                >
                  {isMatchingPrefix ? renderOptionText(option.text, typedBuffer) : option.text}
                </button>
              );
            })}
          </div>

          {/* Keyboard Helper / Search Filter Bar */}
          {status === "idle" && (
            <div className="mt-6 flex flex-col items-center gap-2">
              {typedBuffer.length > 0 ? (
                <div className="flex items-center gap-2 rounded-full border border-duo-blue bg-[#ddf4ff] px-3.5 py-1 text-xs font-black text-[#1899d6] shadow-sm animate-in fade-in zoom-in-95 duration-150 dark:bg-duo-blue/20 dark:text-[#1cb0f6]">
                  <Sparkles className="h-3.5 w-3.5 animate-pulse text-duo-blue" />
                  <span>
                    Matching prefix: &ldquo;{typedBuffer}&rdquo;
                  </span>
                  <button
                    onClick={() => setTypedBuffer("")}
                    className="ml-1 rounded-full p-0.5 hover:bg-duo-blue/20 text-[#1899d6] transition"
                    title="Clear search"
                  >
                    ✕
                  </button>
                </div>
              ) : (
                <div className="flex items-center gap-1.5 text-xs font-extrabold text-gray-400 dark:text-gray-500">
                  <Keyboard className="h-3.5 w-3.5 text-gray-400 dark:text-gray-500" />
                </div>
              )}
            </div>
          )}
        </>
      )}

    </div>
  );
}
