const fs = require('fs');
const path = require('path');

// Complete comprehensive noun and adjective morphology table for Basque
const VOCAB_MORPHOLOGY = [
  // [root, sgDef, sgIndef, plDef, plIndef]
  // Human / Professions / Roles
  ["gizon", "gizona", "gizon bat", "gizonak", "gizon batzuk"],
  ["emakume", "emakumea", "emakume bat", "emakumeak", "emakume batzuk"],
  ["mutil", "mutila", "mutil bat", "mutilak", "mutil batzuk"],
  ["neska", "neska", "neska bat", "neskak", "neska batzuk"],
  ["ume", "umea", "ume bat", "umeak", "ume batzuk"],
  ["haur", "haurra", "haur bat", "haurrak", "haur batzuk"],
  ["ikasle", "ikaslea", "ikasle bat", "ikasleak", "ikasle batzuk"],
  ["irakasle", "irakaslea", "irakasle bat", "irakasleak", "irakasle batzuk"],
  ["mediku", "medikua", "mediku bat", "medikuak", "mediku batzuk"],
  ["erizain", "erizaina", "erizain bat", "erizainak", "erizain batzuk"],
  ["sukaldari", "sukaldaria", "sukaldari bat", "sukaldariak", "sukaldari batzuk"],
  ["gidari", "gidaria", "gidari bat", "gidariak", "gidari batzuk"],
  ["camarero", "camareroa", "camarero bat", "camareroak", "camarero batzuk"],
  ["zerbitzari", "zerbitzaria", "zerbitzari bat", "zerbitzariak", "zerbitzari batzuk"],
  ["apaiz", "apaiza", "apaiz bat", "apaizak", "apaiz batzuk"],
  ["etxekoandre", "etxekoandrea", "etxekoandre bat", "etxekoandreak", "etxekoandre batzuk"],
  ["arrotz", "arrotza", "arrotz bat", "arrotzak", "arrotz batzuk"],
  ["lagun", "laguna", "lagun bat", "lagunak", "lagun batzuk"],
  ["polizia", "polizia", "polizia bat", "poliziak", "polizia batzuk"],
  ["turista", "turista", "turista bat", "turistak", "turista batzuk"],
  ["gida", "gida", "gida bat", "gidak", "gida batzuk"],
  ["tour gida", "tour gida", "tour gida bat", "tour gidak", "tour gida batzuk"],
  ["pertsona", "pertsona", "pertsona bat", "pertsonak", "pertsona batzuk"],
  ["euskaldun", "euskalduna", "euskaldun bat", "euskaldunak", "euskaldun batzuk"],
  ["seme", "semea", "seme bat", "semeak", "seme batzuk"],
  ["alaba", "alaba", "alaba bat", "alabak", "alaba batzuk"],
  ["semealaba", "semealaba", "semealaba bat", "semealabak", "semealaba batzuk"],
  ["semealba", "semealba", "semealba bat", "semealbak", "semealba batzuk"],
  ["aita", "aita", "aita bat", "aitak", "aita batzuk"],
  ["ama", "ama", "ama bat", "amak", "ama batzuk"],
  ["anaia", "anaia", "anaia bat", "anaiak", "anaia batzuk"],
  ["arreba", "arreba", "arreba bat", "arrebak", "arreba batzuk"],
  ["ahizpa", "ahizpa", "ahizpa bat", "ahizpak", "ahizpa batzuk"],
  ["neba", "neba", "neba bat", "nebak", "neba batzuk"],
  ["izeba", "izeba", "izeba bat", "izebak", "izeba batzuk"],
  ["osaba", "osaba", "osaba bat", "osabak", "osaba batzuk"],
  ["aitona", "aitona", "aitona bat", "aitonak", "aitona batzuk"],
  ["amona", "amona", "amona bat", "amonak", "amona batzuk"],
  ["senar", "senarra", "senar bat", "senarrak", "senar batzuk"],
  ["emazte", "emaztea", "emazte bat", "emazteak", "emazte batzuk"],
  ["lehengusu", "lehengusua", "lehengusu bat", "lehengusuak", "lehengusu batzuk"],
  ["mutillagun", "mutillaguna", "mutillagun bat", "mutillagunak", "mutillagun batzuk"],
  ["neskalagun", "neskalaguna", "neskalagun bat", "neskalagunak", "neskalagun batzuk"],
  ["guraso", "gurasoa", "guraso bat", "gurasoak", "guraso batzuk"],
  ["iloba", "iloba", "iloba bat", "ilobak", "iloba batzuk"],
  ["biloba", "biloba", "biloba bat", "bilobak", "biloba batzuk"],
  ["idazle", "idazlea", "idazle bat", "idazleak", "idazle batzuk"],
  ["aktore", "aktorea", "aktore bat", "aktoreak", "aktore batzuk"],
  ["abokatu", "abokatua", "abokatu bat", "abokatuak", "abokatu batzuk"],
  ["arkitekto", "arkitektoa", "arkitekto bat", "arkitektoak", "arkitekto batzuk"],
  ["pilotari", "pilotaria", "pilotari bat", "pilotariak", "pilotari batzuk"],
  ["kantari", "kantaria", "kantari bat", "kantariak", "kantari batzuk"],
  ["dantzari", "dantzaria", "dantzari bat", "dantzariak", "dantzari batzuk"],
  ["txirrindulari", "txirrindularia", "txirrindulari bat", "txirrindulariak", "txirrindulari batzuk"],
  ["futbolari", "futbolaria", "futbolari bat", "futbolariak", "futbolari batzuk"],
  ["arotz", "arotza", "arotz bat", "arotzak", "arotz batzuk"],

  // Animals
  ["animalia", "animalia", "animalia bat", "animaliak", "animalia batzuk"],
  ["txakur", "txakurra", "txakur bat", "txakurrak", "txakur batzuk"],
  ["katu", "katua", "katu bat", "katuak", "katu batzuk"],
  ["zaldi", "zaldia", "zaldi bat", "zaldiak", "zaldi batzuk"],
  ["behi", "behia", "behi bat", "behiak", "behi batzuk"],
  ["txori", "txoria", "txori bat", "txoriak", "txori batzuk"],
  ["arrain", "arraina", "arrain bat", "arrainak", "arrain batzuk"],
  ["otso", "otsoa", "otso bat", "otsoak", "otso batzuk"],
  ["ardi", "ardia", "ardi bat", "ardiak", "ardi batzuk"],
  ["ahuntz", "ahuntza", "ahuntz bat", "ahuntzak", "ahuntz batzuk"],
  ["suge", "sugea", "suge bat", "sugeak", "suge batzuk"],
  ["hontz", "hontza", "hontz bat", "hontzak", "hontz batzuk"],
  ["dortoka", "dortoka", "dortoka bat", "dortokak", "dortoka batzuk"],
  ["txerri", "txerria", "txerri bat", "txerriak", "txerri batzuk"],
  ["oilo", "oiloa", "oilo bat", "oiloak", "oilo batzuk"],
  ["sagu", "sagua", "sagu bat", "saguak", "sagu batzuk"],

  // Inanimate Nouns / Objects / Places
  ["kotxe", "kotxea", "kotxe bat", "kotxeak", "kotxe batzuk"],
  ["auto", "autoa", "auto bat", "autoak", "auto batzuk"],
  ["autobus", "autobusa", "autobus bat", "autobusak", "autobus batzuk"],
  ["tren", "trena", "tren bat", "trenak", "tren batzuk"],
  ["hegazkin", "hegazkina", "hegazkin bat", "hegazkinak", "hegazkin batzuk"],
  ["kamioi", "kamioia", "kamioi bat", "kamioiak", "kamioi batzuk"],
  ["liburu", "liburua", "liburu bat", "liburuak", "liburu batzuk"],
  ["etxe", "etxea", "etxe bat", "etxeak", "etxe batzuk"],
  ["hotel", "hotela", "hotel bat", "hotelak", "hotel batzuk"],
  ["ostatu", "ostatua", "ostatu bat", "ostatuak", "ostatu batzuk"],
  ["denda", "denda", "denda bat", "dendak", "denda batzuk"],
  ["eskola", "eskola", "eskola bat", "eskolak", "eskola batzuk"],
  ["jatetxe", "jatetxea", "jatetxe bat", "jatetxeak", "jatetxe batzuk"],
  ["taberna", "taberna", "taberna bat", "tabernak", "taberna batzuk"],
  ["plaza", "plaza", "plaza bat", "plazak", "plaza batzuk"],
  ["hizkuntza", "hizkuntza", "hizkuntza bat", "hizkuntzak", "hizkuntza batzuk"],
  ["ate", "atea", "ate bat", "ateak", "ate batzuk"],
  ["leiho", "leihoa", "leiho bat", "leihoak", "leiho batzuk"],
  ["mahai", "mahaia", "mahai bat", "mahaiak", "mahai batzuk"],
  ["poltsa", "poltsa", "poltsa bat", "poltsak", "poltsa batzuk"],
  ["zorro", "zorroa", "zorro bat", "zorroak", "zorro batzuk"],
  ["motxila", "motxila", "motxila bat", "motxilak", "motxila batzuk"],
  ["soineko", "soinekoa", "soineko bat", "soinekoak", "soineko batzuk"],
  ["txano", "txanoa", "txano bat", "txanoak", "txano batzuk"],
  ["jertse", "jertsea", "jertse bat", "jertseak", "jertse batzuk"],
  ["alkandora", "alkandora", "alkandora bat", "alkandorak", "alkandora batzuk"],
  ["gona", "gona", "gona bat", "gonak", "gona batzuk"],
  ["beroki", "berokia", "beroki bat", "berokiak", "beroki batzuk"],
  ["sagar", "sagarra", "sagar bat", "sagarrak", "sagar batzuk"],
  ["banana", "banana", "banana bat", "bananak", "banana batzuk"],
  ["limoi", "limoia", "limoi bat", "limoiak", "limoi batzuk"],
  ["madari", "madaria", "madari bat", "madariak", "madari batzuk"],
  ["marrubi", "marrubia", "marrubi bat", "marrubiak", "marrubi batzuk"],
  ["melokotoi", "melokotoia", "melokotoi bat", "melokotoiak", "melokotoi batzuk"],
  ["urtaro", "urtaroa", "urtaro bat", "urtaroak", "urtaro batzuk"],
  ["egun", "eguna", "egun bat", "egunak", "egun batzuk"],
  ["hilabete", "hilabetea", "hilabete bat", "hilabeteak", "hilabete batzuk"],
  ["urte", "urtea", "urte bat", "urteak", "urte batzuk"],
  ["baloi", "baloia", "baloi bat", "baloiak", "baloi batzuk"],
  ["baserri", "baserria", "baserri bat", "baserriak", "baserri batzuk"],
  ["baso", "basoa", "baso bat", "basoak", "baso batzuk"],
  ["laku", "lakua", "laku bat", "lakuak", "laku batzuk"],
  ["ibai", "ibaia", "ibai bat", "ibaiak", "ibai batzuk"],
  ["mendi", "mendia", "mendi bat", "mendiak", "mendi batzuk"],
  ["itsaso", "itsasoa", "itsaso bat", "itsasoak", "itsaso batzuk"],
  ["herri", "herria", "herri bat", "herriak", "herri batzuk"],
  ["hiri", "hiria", "hiri bat", "hiriak", "hiri batzuk"],
  ["bide", "bidea", "bide bat", "bideak", "bide batzuk"],
  ["kale", "kalea", "kale bat", "kaleak", "kale batzuk"],
  ["eliza", "eliza", "eliza bat", "elizak", "eliza batzuk"],
  ["banku", "bankua", "banku bat", "bankuak", "banku batzuk"],
  ["geltoki", "geltokia", "geltoki bat", "geltokiak", "geltoki batzuk"],
  ["horma", "horma", "horma bat", "hormak", "horma batzuk"],
  ["teilatu", "teilatua", "teilatu bat", "teilatuak", "teilatu batzuk"],
  ["aulki", "aulkia", "aulki bat", "aulkiak", "aulki batzuk"],
  ["erloju", "erlojua", "erloju bat", "erlojuak", "erloju batzuk"],
  ["betaurreko", "betaurrekoa", "betaurreko bat", "betaurrekoak", "betaurreko batzuk"],
  ["eraztun", "eraztuna", "eraztun bat", "eraztunak", "eraztun batzuk"],
  ["galtzerdi", "galtzerdia", "galtzerdi bat", "galtzerdiak", "galtzerdi batzuk"],
  ["zapata", "zapata", "zapata bat", "zapatak", "zapata batzuk"],
  ["boligrafo", "boligrafoa", "boligrafo bat", "boligrafoak", "boligrafo batzuk"],
  ["luma", "luma", "luma bat", "lumak", "luma batzuk"],
  ["paper", "papera", "paper bat", "paperak", "paper batzuk"],
  ["koaderno", "koadernoa", "koaderno bat", "koadernoak", "koaderno batzuk"],
  ["ekaitz", "ekaitza", "ekaitz bat", "ekaitzak", "ekaitz batzuk"],
  ["euri", "euria", "euri bat", "euriak", "euri batzuk"],
  ["elur", "elurra", "elur bat", "elurrak", "elur batzuk"],
  ["haize", "haizea", "haize bat", "haizeak", "haize batzuk"],
  ["laino", "lainoa", "laino bat", "lainoak", "laino batzuk"],
  ["uharte", "uhartea", "uharte bat", "uharteak", "uharte batzuk"],
  ["zuhaitz", "zuhaitza", "zuhaitz bat", "zuhaitzak", "zuhaitz batzuk"],
  ["lore", "lorea", "lore bat", "loreak", "lore batzuk"],
  ["hosto", "hostoa", "hosto bat", "hostoak", "hosto batzuk"],
  ["sagardo", "sagardoa", "sagardo bat", "sagardoak", "sagardo batzuk"],
  ["ardo", "ardoa", "ardo bat", "ardoak", "ardo batzuk"],
  ["garagardo", "garagardoa", "garagardo bat", "garagardoak", "garagardo batzuk"],
  ["ur", "ura", "ur bat", "urak", "ur batzuk"],
  ["esne", "esnea", "esne bat", "esneak", "esne batzuk"],
  ["kafe", "kafea", "kafe bat", "kafeak", "kafe batzuk"],
  ["te", "tea", "te bat", "teak", "te batzuk"],
  ["ogi", "ogia", "ogi bat", "ogiak", "ogi batzuk"],
  ["gazta", "gazta", "gazta bat", "gaztak", "gazta batzuk"],
  ["haragi", "haragia", "haragi bat", "haragiak", "haragi batzuk"],
  ["barazki", "barazkia", "barazki bat", "barazkiak", "barazki batzuk"],
  ["entsalada", "entsalada", "entsalada bat", "entsaladak", "entsalada batzuk"],
  ["zopa", "zopa", "zopa bat", "zopak", "zopa batzuk"],
  ["postre", "postrea", "postre bat", "postreak", "postre batzuk"],
  ["tarta", "tarta", "tarta bat", "tartak", "tarta batzuk"],
  ["izozki", "izozkia", "izozki bat", "izozkiak", "izozki batzuk"],
  ["gozoki", "gozokia", "gozoki bat", "gozokiak", "gozoki batzuk"],
  ["gosari", "gosaria", "gosari bat", "gosariak", "gosari batzuk"],
  ["bazkari", "bazkaria", "bazkari bat", "bazkariak", "bazkari batzuk"],
  ["afari", "afaria", "afari bat", "afariak", "afari batzuk"],
  ["botila", "botila", "botila bat", "botilak", "botila batzuk"],
  ["edalontzi", "edalontzia", "edalontzi bat", "edalontziak", "edalontzi batzuk"],
  ["plater", "platera", "plater bat", "platerak", "plater batzuk"],
  ["koilara", "koilara", "koilara bat", "koilarak", "koilara batzuk"],
  ["sardexka", "sardexka", "sardexka bat", "sardexkak", "sardexka batzuk"],
  ["labana", "labana", "labana bat", "labanak", "labana batzuk"],
  ["kolore", "kolorea", "kolore bat", "koloreak", "kolore batzuk"],

  // Adjectives
  ["argal", "argala", "argal bat", "argalak", "argal batzuk"],
  ["lodi", "lodia", "lodi bat", "lodiak", "lodi batzuk"],
  ["gizen", "gizena", "gizen bat", "gizenak", "gizen batzuk"],
  ["altu", "altua", "altu bat", "altuak", "altu batzuk"],
  ["motz", "motza", "motz bat", "motzak", "motz batzuk"],
  ["zahar", "zaharra", "zahar bat", "zaharrak", "zahar batzuk"],
  ["zahar", "zahara", "zahar bat", "zaharak", "zahar batzuk"],
  ["gazte", "gaztea", "gazte bat", "gazteak", "gazte batzuk"],
  ["txiki", "txikia", "txiki bat", "txikiak", "txiki batzuk"],
  ["handi", "handia", "handi bat", "handiak", "handi batzuk"],
  ["polit", "polita", "polit bat", "politak", "polit batzuk"],
  ["eder", "ederra", "eder bat", "ederrak", "eder batzuk"],
  ["itsusi", "itsusia", "itsusi bat", "itsusiak", "itsusi batzuk"],
  ["on", "ona", "on bat", "onak", "on batzuk"],
  ["txar", "txarra", "txar bat", "txarrak", "txar batzuk"],
  ["azkar", "azkarra", "azkar bat", "azkarrak", "azkar batzuk"],
  ["motel", "motela", "motel bat", "motelak", "motel batzuk"],
  ["berri", "berria", "berri bat", "berriak", "berri batzuk"],
  ["indartsu", "indartsua", "indartsu bat", "indartsuak", "indartsu batzuk"],
  ["ahul", "ahula", "ahul bat", "ahulak", "ahul batzuk"],
  ["jator", "jatorra", "jator bat", "jatorrak", "jator batzuk"],
  ["bakar", "bakarra", "bakar bat", "bakarrak", "bakar batzuk"],
  ["luze", "luzea", "luze bat", "luzeak", "luze batzuk"],
  ["labur", "laburra", "labur bat", "laburrak", "labur batzuk"],
  ["zuri", "zuria", "zuri bat", "zuriak", "zuri batzuk"],
  ["beltz", "beltza", "beltz bat", "beltzak", "beltz batzuk"],
  ["gorri", "gorria", "gorri bat", "gorriak", "gorri batzuk"],
  ["berde", "berdea", "berde bat", "berdeak", "berde batzuk"],
  ["hori", "horia", "hori bat", "horiak", "hori batzuk"],
  ["urdin", "urdina", "urdin bat", "urdinak", "urdin batzuk"],
  ["laranja", "laranja", "laranja bat", "laranjak", "laranja batzuk"],
  ["more", "morea", "more bat", "moreak", "more batzuk"],
  ["gris", "grisa", "gris bat", "grisak", "gris batzuk"],
  ["marroi", "marroia", "marroi bat", "marroiak", "marroi batzuk"],
  ["busti", "bustia", "busti bat", "bustiak", "busti batzuk"],
  ["lehor", "lehorra", "lehor bat", "lehorrak", "lehor batzuk"],
  ["bero", "beroa", "bero bat", "beroak", "bero batzuk"],
  ["hotz", "hotza", "hotz bat", "hotzak", "hotz batzuk"],
  ["garbi", "garbia", "garbi bat", "garbiak", "garbi batzuk"],
  ["zikin", "zikina", "zikin bat", "zikinak", "zikin batzuk"],
  ["libre", "librea", "libre bat", "libreak", "libre batzuk"],
  ["okupatu", "okupatua", "okupatu bat", "okupatuak", "okupatu batzuk"],
  ["lanpetu", "lanpetua", "lanpetu bat", "lanpetuak", "lanpetu batzuk"],
  ["aspertu", "aspertua", "aspertu bat", "aspertuak", "aspertu batzuk"],
  ["beldurti", "beldurtia", "beldurti bat", "beldurtiak", "beldurti batzuk"],
  ["alai", "alaia", "alai bat", "alaiak", "alai batzuk"],
  ["triste", "tristea", "triste bat", "tristeak", "triste batzuk"],
  ["pobre", "pobrea", "pobre bat", "pobreak", "pobre batzuk"],
  ["aberats", "aberatsa", "aberats bat", "aberatsak", "aberats batzuk"]
];

const PRED_SG_DEF_TO_INDEF = new Map();
const PRED_SG_INDEF_TO_DEF = new Map();
const PRED_PL_DEF_TO_INDEF = new Map();
const PRED_PL_INDEF_TO_DEF = new Map();

VOCAB_MORPHOLOGY.forEach(([root, sgDef, sgIndef, plDef, plIndef]) => {
  PRED_SG_DEF_TO_INDEF.set(sgDef.toLowerCase(), sgIndef.toLowerCase());
  PRED_SG_INDEF_TO_DEF.set(sgIndef.toLowerCase(), sgDef.toLowerCase());
  PRED_PL_DEF_TO_INDEF.set(plDef.toLowerCase(), plIndef.toLowerCase());
  PRED_PL_INDEF_TO_DEF.set(plIndef.toLowerCase(), plDef.toLowerCase());
  
  if (root.toLowerCase() !== sgDef.toLowerCase()) {
    PRED_SG_DEF_TO_INDEF.set(root.toLowerCase(), sgIndef.toLowerCase());
  }
});

console.log(`Loaded ${VOCAB_MORPHOLOGY.length} vocabulary morphology entries.`);

module.exports = {
  VOCAB_MORPHOLOGY,
  PRED_SG_DEF_TO_INDEF,
  PRED_SG_INDEF_TO_DEF,
  PRED_PL_DEF_TO_INDEF,
  PRED_PL_INDEF_TO_DEF
};
